# Generated by Django 3.2 on 2023-12-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='../account_default_i3pomf', upload_to='images/'),
        ),
    ]
