# Generated by Django 3.2 on 2024-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='../account_default_lhrxjr', upload_to='images/'),
        ),
    ]
